use anyhow::Result;
use clap::Parser;
use draco_oxide::prelude::ConfigType;
use std::path::Path;

#[derive(Parser)]
#[command(name = "draco-cli")]
#[command(about = "A CLI tool for Draco mesh compression")]
struct Cli {
    /// Input file path
    #[arg(short, long)]
    input: String,

    /// Output file path
    #[arg(short, long)]
    output: String,

    /// Transcode mode for glTF/GLB files (compress with Draco)
    #[arg(long)]
    transcode: bool,

    /// Decode mode: read a .drc file and write a .obj.
    #[arg(long)]
    decode: bool,

    /// Decode-glb mode: read a .glb with KHR_draco_mesh_compression
    /// and dump per-primitive stats to stderr (no output file written).
    #[arg(long)]
    decode_glb: bool,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    if cli.transcode {
        transcode_gltf(&cli.input, &cli.output)
    } else if cli.decode {
        decode_drc_to_obj(&cli.input, &cli.output)
    } else if cli.decode_glb {
        decode_glb_inspect(&cli.input)
    } else {
        convert_obj_to_drc(&cli.input, &cli.output)
    }
}

fn decode_glb_inspect(input_path: &str) -> Result<()> {
    let glb = std::fs::read(input_path)
        .map_err(|e| anyhow::anyhow!("Failed to read input file: {}", e))?;
    eprintln!("glb size: {} bytes", glb.len());
    let decoded = draco_oxide::io::gltf::draco_decoder::decode_glb(&glb)
        .map_err(|e| anyhow::anyhow!("Decode failed: {:?}", e))?;
    eprintln!("decoded {} Draco primitives", decoded.len());
    for p in &decoded {
        eprintln!(
            "  primitive {}/{}: {} faces",
            p.mesh_idx,
            p.primitive_idx,
            p.mesh.get_faces().len()
        );
        for a in p.mesh.get_attributes() {
            eprintln!(
                "    attr type={:?} comp={} len={}",
                a.get_attribute_type(),
                a.get_num_components(),
                a.len()
            );
        }
    }
    Ok(())
}

fn decode_drc_to_obj(input_path: &str, output_path: &str) -> Result<()> {
    let input_ext = Path::new(input_path)
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    if input_ext != "drc" {
        anyhow::bail!("Input file must be a .drc file for decode mode");
    }
    let output_ext = Path::new(output_path)
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    if output_ext != "obj" {
        anyhow::bail!("Output file must be a .obj file for decode mode");
    }

    let buf = std::fs::read(input_path)
        .map_err(|e| anyhow::anyhow!("Failed to read input file: {}", e))?;
    let mut reader = buf.into_iter();
    let mesh = draco_oxide::decode::decode(&mut reader, draco_oxide::decode::Config::default())
        .map_err(|e| anyhow::anyhow!("Failed to decode mesh: {:?}", e))?;

    let pos_att = mesh
        .get_attributes()
        .iter()
        .find(|a| a.get_attribute_type() == draco_oxide::prelude::AttributeType::Position)
        .ok_or_else(|| anyhow::anyhow!("Decoded mesh has no position attribute"))?;

    use draco_oxide::prelude::{AttributeType, NdVector, PointIdx, Vector};
    let normal_att = mesh
        .get_attributes()
        .iter()
        .find(|a| a.get_attribute_type() == AttributeType::Normal);
    let uv_att = mesh
        .get_attributes()
        .iter()
        .find(|a| a.get_attribute_type() == AttributeType::TextureCoordinate);

    let mut out = String::new();
    out.push_str("# Generated by draco-oxide CLI decode\n");
    for i in 0..pos_att.len() {
        let v: NdVector<3, f32> = pos_att.get(PointIdx::from(i));
        out.push_str(&format!("v {} {} {}\n", *v.get(0), *v.get(1), *v.get(2)));
    }
    if let Some(n) = normal_att {
        for i in 0..n.len() {
            let v: NdVector<3, f32> = n.get(PointIdx::from(i));
            out.push_str(&format!("vn {} {} {}\n", *v.get(0), *v.get(1), *v.get(2)));
        }
    }
    if let Some(t) = uv_att {
        for i in 0..t.len() {
            let v: NdVector<2, f32> = t.get(PointIdx::from(i));
            out.push_str(&format!("vt {} {}\n", *v.get(0), *v.get(1)));
        }
    }
    let has_n = normal_att.is_some();
    let has_t = uv_att.is_some();
    for f in mesh.get_faces() {
        let i0 = usize::from(f[0]) + 1;
        let i1 = usize::from(f[1]) + 1;
        let i2 = usize::from(f[2]) + 1;
        let render = |i: usize| -> String {
            match (has_t, has_n) {
                (true, true) => format!("{}/{}/{}", i, i, i),
                (true, false) => format!("{}/{}", i, i),
                (false, true) => format!("{}//{}", i, i),
                (false, false) => format!("{}", i),
            }
        };
        out.push_str(&format!("f {} {} {}\n", render(i0), render(i1), render(i2)));
    }
    std::fs::write(output_path, out)
        .map_err(|e| anyhow::anyhow!("Failed to write output file: {}", e))?;
    eprintln!(
        "decoded {} vertices, {} faces → {}",
        pos_att.len(),
        mesh.get_faces().len(),
        output_path
    );
    Ok(())
}

fn convert_obj_to_drc(input_path: &str, output_path: &str) -> Result<()> {
    // Check input file extension
    let input_ext = Path::new(input_path)
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("");

    if input_ext != "obj" {
        anyhow::bail!("Input file must be a .obj file for conversion mode");
    }

    // Check output file extension
    let output_ext = Path::new(output_path)
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("");

    if output_ext != "drc" {
        anyhow::bail!("Output file must be a .drc file for conversion mode");
    }

    // Load OBJ file using draco-oxide's OBJ loader
    let mesh = draco_oxide::io::obj::load_obj(input_path)
        .map_err(|e| anyhow::anyhow!("Failed to load OBJ file: {:?}", e))?;

    // Configure compression settings
    let config = draco_oxide::encode::Config::default();

    // Encode the mesh to a buffer
    let mut buffer = Vec::new();
    draco_oxide::encode::encode(mesh, &mut buffer, config)
        .map_err(|e| anyhow::anyhow!("Failed to encode mesh: {:?}", e))?;

    // Write to output file
    std::fs::write(output_path, buffer)
        .map_err(|e| anyhow::anyhow!("Failed to write output file: {}", e))?;

    Ok(())
}

fn transcode_gltf(input_path: &str, output_path: &str) -> Result<()> {
    // Check input file extension
    let input_ext = Path::new(input_path)
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("");

    if !matches!(input_ext, "gltf" | "glb") {
        anyhow::bail!("Input file must be a .gltf or .glb file for transcode mode");
    }

    // Check output file extension
    let output_ext = Path::new(output_path)
        .extension()
        .and_then(|s| s.to_str())
        .unwrap_or("");

    if !matches!(output_ext, "gltf" | "glb") {
        anyhow::bail!("Output file must be a .gltf or .glb file for transcode mode");
    }

    // Read input file
    let input = std::fs::read(input_path)
        .map_err(|e| anyhow::anyhow!("Failed to read input file: {}", e))?;

    // Create transcoder and transcode
    let transcoder = draco_oxide::io::gltf::GltfTranscoder::default();
    let warnings = transcoder
        .transcode_to_file(&input, Path::new(output_path))
        .map_err(|e| anyhow::anyhow!("Failed to transcode: {}", e))?;

    // Print any warnings
    for warning in warnings {
        eprintln!("Warning: {}", warning);
    }

    Ok(())
}
